### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by alexpro401** [HcashOrg/HyperExchange#1]
Hello, I am very interested in your development Graphene - Crosschain, how can we contact you?

**Comment by realm520** [comment]
Please mail to hyperexchange@h.cash.

**Comment by bitoo** [comment]
It is our honor of your feedback .  


any question pls ask blow;
twitter :   @AnyBit9
Email: HyperExchange@h.cash



info@blocklinker.com
 
From: alexpro401
Date: 2018-07-30 14:00
To: HcashOrg/HyperExchange
CC: Subscribed
Subject: [HcashOrg/HyperExchange] Cooperation (#1)
Hello, I am very interested in your development Graphene - Crosschain, how can we contact you?
