### ISSUE TITLE
更新到1.1.7或1.1.8，replaying的时候会报Block 81189 doen't exist.

### ISSUE THREAD

**Issue by chengxulvtu** [HcashOrg/HyperExchange#10]
HXIndicator更新到1.1.7或1.1.8，打开后，会有Replaying，然后就会报如下图所示的错误：
![image](https://user-images.githubusercontent.com/949848/49227716-b8ba0980-f424-11e8-9568-a4cb8b2bf5d0.png)

**Comment by zoowii** [comment]
1.1.8中有修复一个之前版本分红时链上分红了但是未正常显示的BUG，需要replay整个链。如果这个版本更新中遇到图中的报错 Block xxxxx does not exist，请关闭钱包，确保已经备份了wallet.json后，删除数据目录(默认在%APPDATA%下)chaindata下的blockchain文件夹。如果重启依然报错并且提示logging config有错误，关闭钱包，删除chaindata文件夹下的blockchain文件夹,logs文件夹，peers文件夹，以及config.ini文件，然后重启。注意删除config.ini后citizen挖矿需要重新开启

**Comment by chengxulvtu** [comment]
好的，另外 CITIZEN权重越高，需要的服务器配置是不是要越高？

**Comment by zoowii** [comment]
并不是。citizen对配置要求都一样，其实都不太高但是也不能太低，否则会比较慢。长期考虑建议用8G以上内存电脑运行citizen

**Comment by chengxulvtu** [comment]
好的，非常感谢
