### ISSUE TITLE
build fail on ubuntu16.0.4

### ISSUE THREAD

**Issue by hunjixin** [HcashOrg/HyperExchange#2]
[ 48%] Building CXX object libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/private_key.cpp.o
/home/hunjixin/Desktop/code/HyperExchange/libraries/crosschain_privatekey_management/private_key.cpp:16:31: fatal error: bitcoin/bitcoin.hpp: No such file or directory
compilation terminated.
libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/build.make:62: recipe for target 'libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/private_key.cpp.o' failed
make[2]: *** [libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/private_key.cpp.o] Error 1
CMakeFiles/Makefile2:1420: recipe for target 'libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/all' failed
make[1]: *** [libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ElleryHao** [comment]
hello, please check the following web page , which can help your building
http://docs.hx.cash/wallets/hx-building/

**Comment by hunjixin** [comment]
I have operated according to the document, but I still reported it wrong.

**Comment by ElleryHao** [comment]
> I have operated according to the document, but I still reported it wrong.
the same as before?

**Comment by hunjixin** [comment]
`export CROSSCHAIN_PRIVATEKEY_PROJECT=~/blocklink_crosschain_privatekey`
environment path is git code directory??



```
[ 48%] Building CXX object libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/private_key.cpp.o
/home/hunjixin/Desktop/code/HyperExchange/libraries/crosschain_privatekey_management/private_key.cpp:16:31: fatal error: bitcoin/bitcoin.hpp: No such file or directory
compilation terminated.
libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/build.make:62: recipe for target 'libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/private_key.cpp.o' failed
make[2]: *** [libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/private_key.cpp.o] Error 1
CMakeFiles/Makefile2:1420: recipe for target 'libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/all' failed
make[1]: *** [libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2


```

bitcoin cpp??

**Comment by ElleryHao** [comment]
> `export CROSSCHAIN_PRIVATEKEY_PROJECT=~/blocklink_crosschain_privatekey`
> environment path is git code directory??
> 
> ```
> [ 48%] Building CXX object libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/private_key.cpp.o
> /home/hunjixin/Desktop/code/HyperExchange/libraries/crosschain_privatekey_management/private_key.cpp:16:31: fatal error: bitcoin/bitcoin.hpp: No such file or directory
> compilation terminated.
> libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/build.make:62: recipe for target 'libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/private_key.cpp.o' failed
> make[2]: *** [libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/private_key.cpp.o] Error 1
> CMakeFiles/Makefile2:1420: recipe for target 'libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/all' failed
> make[1]: *** [libraries/crosschain_privatekey_management/CMakeFiles/crosschain_privatekey_management.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
> bitcoin cpp??

1. build project blocklink_crosschain_privatekey first
2. set environment CROSSCHAIN_PRIVATEKEY_PROJECT with full path of  blocklink_crosschain_privatekey
3.build project HX

so check if CROSSCHAIN_PRIVATEKEY_PROJECT  is valid or not

**Comment by hunjixin** [comment]
i has echo the environment CROSSCHAIN_PRIVATEKEY_PROJECT,

```
hunjixin@hunjixin-Battle-Axe-C-B360M-HD:~/Desktop/code/HyperExchange$ echo $CROSSCHAIN_PRIVATEKEY_PROJECT
/home/hunjixin/Desktop/code/blocklink_crosschain_privatekey/
```

**Comment by ElleryHao** [comment]
> i has echo the environment CROSSCHAIN_PRIVATEKEY_PROJECT,
> 
> ```
> hunjixin@hunjixin-Battle-Axe-C-B360M-HD:~/Desktop/code/HyperExchange$ echo $CROSSCHAIN_PRIVATEKEY_PROJECT
> /home/hunjixin/Desktop/code/blocklink_crosschain_privatekey/
> ```

1. have u built the project blocklink_crosschain_privatekey successfully
2. is the path of /home/inchain/compile_blocklink/blocklink_crosschain_privatekey correct
i think if both the above are correct, the building should have been successful

**Comment by hunjixin** [comment]
Q_Q  path is correct

**Comment by ElleryHao** [comment]
the first step is also very important

**Comment by hunjixin** [comment]
success after deleling and repeate the operation


then anyway to generate key pair?

**Comment by ElleryHao** [comment]
> success after deleling and repeate the operation
> 
> then anyway to generate key pair?

if you wanna build a private test-net , i think u should check http://docs.hx.cash/getting-started/private-testnet/
