### ISSUE TITLE
import_balance not implemented ?

### ISSUE THREAD

**Issue by hunjixin** [HcashOrg/HyperExchange#3]
import_balance nathan ["5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"] true
10 assert_exception: Assert Exception
itr != _by_name.end(): no method with name 'import_balance'

**Comment by ElleryHao** [comment]
this function  has been abandoned

**Comment by hunjixin** [comment]
> this function has been abandoned

where to get origin asset?

**Comment by ElleryHao** [comment]
> > this function has been abandoned
> 
> where to get origin asset?

just import_key nathan, it is different from BTS in balance management
