### ISSUE TITLE
充值hc不到账

### ISSUE THREAD

**Issue by chengxulvtu** [HcashOrg/HyperExchange#4]
往地址：HsWPTWNx2jhXaYTy29nGCr4xdz5iPiewtCF 充值hc，在HXIndicator里面看不到余额

**Comment by zoowii** [comment]
http://explorer.h.cash/address/HsWPTWNx2jhXaYTy29nGCr4xdz5iPiewtCF

hc的区块浏览器中没看到这个地址有HC到账

**Comment by zoowii** [comment]
![image](https://user-images.githubusercontent.com/1117606/48890861-f216d600-ee74-11e8-87ef-bcd67457e5b5.png)

请点击划转

**Comment by chengxulvtu** [comment]
划转了，
![image](https://user-images.githubusercontent.com/949848/48891883-90a43680-ee77-11e8-8cf4-a124ad56dbd0.png)

余额还是都为0,10几分钟了

**Comment by chengxulvtu** [comment]
在mac下失败
![image](https://user-images.githubusercontent.com/949848/48892151-4e2f2980-ee78-11e8-86a7-541226ab1f68.png)

**Comment by chengxulvtu** [comment]
> 划转了，
> ![image](https://user-images.githubusercontent.com/949848/48891883-90a43680-ee77-11e8-8cf4-a124ad56dbd0.png)
> 
> 余额还是都为0,10几分钟了

到账了

**Comment by zoowii** [comment]
HC链上到账比较慢，刚看到这笔划转5个确认了，查看HX上地址你充值的HC已经到账了。

第二个转账失败的图，应该是你这个mac电脑上使用的wallet.json不是最新的，请在其他设备上导出最新的wallet.json并在mac上重新导入。

另外，尽量不要在多设备上同时使用同样钱包账户，否则wallet.json的版本有可能不太好管理可能不是用的最新的。

**Comment by chengxulvtu** [comment]
我朋友的mac安装不上
![image](https://user-images.githubusercontent.com/949848/48892533-4459f600-ee79-11e8-8362-863a9cd8134d.png)

需要系统版本多少？

**Comment by zoowii** [comment]
这个报错有可能是文件下载不完整或者下载过程中报错。
另外，Mac版本我们使用的是10.13或以上

**Comment by chengxulvtu** [comment]
好的，谢谢。我的10.14没问题
