### ISSUE TITLE
哪里下载deploy_data.zip

### ISSUE THREAD

**Issue by chengxulvtu** [HcashOrg/HyperExchange#5]
docker部署，文档上说在官网 hx.cash上下载deploy_data.zip，但是没有找到啊

**Comment by zoowii** [comment]
https://github.com/BlockLink/Docker-Deploy
目前提供的install.sh和install_regtest.sh脚本分别是公测链和本地测试链的，hx正式链环境需要third_chain文件夹中一些参数取消-testnet参数

**Comment by chengxulvtu** [comment]
好的，谢谢
