### ISSUE TITLE
使用docker部署，同步区块数据很慢

### ISSUE THREAD

**Issue by chengxulvtu** [HcashOrg/HyperExchange#8]
我现在在ubuntu 16.04上用docker部署的，同步区块数据好慢啊，有没有已经同步好的一部分区块数据，提供下载？

**Comment by zoowii** [comment]
哪个钱包同步慢？hx的话目前数据量很小，其他btc/eth/ltc/hc的话要看具体网络因素了，这个直接取的这些链的数据

**Comment by chengxulvtu** [comment]
third-chain. 我docker部署的，同步了几个小时，不过现在同步完了。但是使用./hcwallet --create 创建钱包时，输入确认密码后，回车没有反应。

**Comment by chengxulvtu** [comment]
third-chain. 我docker部署的，同步了几个小时，不过现在同步完了。

**Comment by zoowii** [comment]
third_chain如果不是跑regtest本地测试链，是同步很慢的，因为这是同步第三方的btc/ltc/hc/eth钱包

另外，geth需要额外启动，没有放在docker-compose里面启动，有start_geth.sh,start_geth_regtest.sh, start_geth_testnet.sh三个脚本分别对应正式，本地测试，公测链的eth钱包启动。执行前需要执行下source set_env.sh脚本设置环境变量

**Comment by zoowii** [comment]
third_chain如果不是跑regtest本地测试链，是同步很慢的，因为这是同步第三方的btc/ltc/hc/eth钱包

另外，geth需要额外启动，没有放在docker-compose里面启动，有start_geth.sh,start_geth_regtest.sh, start_geth_testnet.sh三个脚本分别对应正式，本地测试，公测链的eth钱包启动。执行前需要执行下source set_env.sh脚本设置环境变量

**Comment by chengxulvtu** [comment]
好的。

还有个问题，就是HX挖矿，如果我在两台服务器上的两个钱包里，导入了同一个CITIZEN账户，对挖矿有什么影响吗？

**Comment by zoowii** [comment]
不要这么做，目前这样做会容易降低citizen的参与率，后期可能被共识制裁，因为这样相当于同一个citizen在一轮出块周期中产生2个不同的块

**Comment by chengxulvtu** [comment]
好的
